server:
  port: 8000

spring:
  application:
    name: SERVE-CONFIG
  profiles:
    #启用本地配置文件
    active: native
  cloud:
    config:
      server:
        native:
          #配置文件扫描目录
          search-locations: classpath:/config/